version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json

  app:
    image: transaction-process-system:latest
    container_name: transaction-process-system
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/transactiondb
      SPRING_RABBITMQ_HOST: rabbitmq
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  rabbitmq_data:
  rabbitmq_logs: